---
- name: cek status cluster
  hosts: {{ curr_master_node }}
  become: true

  tasks:
    - name: cek efm cluster-status
      command: /usr/edb/efm-4.1/bin/efm cluster-status efm
      register: cluster

    - debug: var=cluster.stdout_lines