---
- name: copy config
  hosts: all
  become: true

  tasks:
    - name: copy master config
      copy:
        src: ./files/postgresql-master.conf
        dest: /home/atmo/postgresql-mojo.conf
        owner: enterprisedb
        group: enterprisedb