---
- name: copy config
  hosts: all
  become: true

  tasks:
    - name: copy master config
      copy:
        src: ./files/postgresql-master.conf
        dest: /data/PostgresPlus/9.3AS/data/postgresql.conf
        owner: enterprisedb
        group: enterprisedb